name: Build ARMv7 Nightly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Build in armv7 container
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: armv7
        distro: ubuntu_latest

        # Not required, but speeds up builds by storing container images in
        # a GitHub package registry.
        githubToken: ${{ github.token }}

        install: |
          apt-get update && apt-get -y install \
          btrfs-progs \
          git \
          golang-go \
          go-md2man \
          iptables \
          libassuan-dev \
          libbtrfs-dev \
          libc6-dev \
          libdevmapper-dev \
          libglib2.0-dev \
          libgpgme-dev \
          libgpg-error-dev \
          libprotobuf-dev \
          libprotobuf-c-dev \
          libseccomp-dev \
          libselinux1-dev \
          libsystemd-dev \
          pkg-config \
          runc \
          uidmap \
          build-essential

        run: |
          git config --global --add safe.directory /home/runner/work/podman/podman
          GOOS=linux
          GOARM=7
          GOARCH=arm
          make BUILDTAGS="seccomp"
          make podman-release
          
    - uses: actions/upload-artifact@v3
      with:
        name: podman-release
        path: ./podman-*.tar.gz
